services:

  firebird:
    container_name: firebird
    image: jacobalberty/firebird:${FIREBIRD_VERSION}
    environment:
      TZ: Europe/Paris
      FIREBIRD_DATABASE: boilerplate
      FIREBIRD_USER: admin
      FIREBIRD_PASSWORD: ${FIREBIRD_PASSWORD}
      ISC_PASSWORD: ${FIREBIRD_PASSWORD}
    volumes:
      - ./data:/firebird
