services:

  neo4j:
    container_name: neo4j
    image: neo4j:5.18.1-community
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./data:/data
    environment:
      NEO4J_AUTH: neo4j/mypassword
