global:
  scrape_interval:     5s

scrape_configs:
  - job_name: prometheus
    metrics_path: /prometheus/metrics
    static_configs:
      - targets:
          - '127.0.0.1:9090'

  - job_name: promtail
    metrics_path: /promtail/metrics
    static_configs:
      - targets:
          - 'promtail:80'

  - job_name: traefik
    static_configs:
      - targets:
          - 'proxy:8080'

  - job_name: minio
    metrics_path: /minio/v2/metrics/bucket
    scheme: http
    static_configs:
      - targets:
          - 'minio:9000'

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alertmanager:9093' ]
