networks:
  pgadmin_network:
    name: pgadmin_network
    external: true

services:

  postgres:
    container_name: postgresql
    build:
      context: .
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB} 
    ports:
      - 5432:5432
    networks:
      - pgadmin_network
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
      - ./data/:/var/lib/postgresql/data

