networks:
  host_bridge:
    external: true
  postgresql_internal:
    name: postgresql_internal
    internal: true

configs:
  postgresql_config:
    file: ./initdb.d

services:

  postgresql:
    image: boilerplate/postgresql:2024.03
    container_name: postgresql
    build:
      context: .
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    networks:
      - postgresql_internal
      - host_bridge
    configs:
      - source: postgresql_config
        target: /docker-entrypoint-initdb.d/
    volumes:
      - ./data/:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d ${POSTGRES_DB}'"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s

  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    container_name: postgres-exporter
    networks:
      - postgresql_internal
      - host_bridge
    ports:
      - 9187:9187
    environment:
      DATA_SOURCE_NAME: postgresql://postgres:supermotdepasse@postgresql:5432/postgres?sslmode=disable
