networks:
  postgresql_internal:
    name: postgresql_internal
    driver: bridge
  proxy_internal:
    external: true
  host_bridge:
    external: true

configs:
  postgresql_initdb:
    file: ./initdb.d
  pgadmin_config:
    file: ./pgadmin-servers.json

services:

  postgresql:
    image: boilerplate/postgresql:2024.03
    container_name: postgresql
    build:
      context: .
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    networks:
      - postgresql_internal
    configs:
      - source: postgresql_initdb
        target: /docker-entrypoint-initdb.d/
    volumes:
      - ./data/postgresql/:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d ${POSTGRES_DB}'"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s

  postgres-metrics-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    container_name: prometheus-exporter
    depends_on:
      - postgresql
    networks:
      - postgresql_internal
      - host_bridge
    ports:
      - 9187:9187
    environment:
      DATA_SOURCE_NAME: postgresql://postgres:supermotdepasse@postgresql:5432/postgres?sslmode=disable

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:${PGADMIN_VERSION:-8.4}
    depends_on:
      - postgresql
    restart: no
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_DISABLE_POSTFIX: true
      SCRIPT_NAME: /pgadmin
    configs:
      - source: pgadmin_config
        target: /pgadmin4/servers.json
    volumes:
      - ./data/pgadmin/:/var/lib/pgadmin/
    networks:
      - proxy_internal
      - postgresql_internal
    labels:
      traefik.enable: true
      traefik.http.routers.pgadmin.entrypoints: websecure
      traefik.http.routers.pgadmin.tls: true
      traefik.http.routers.pgadmin.rule: ${PGADMIN_TRAEFIK_RULE}
      traefik.http.services.pgadmin.loadbalancer.server.port: 80
