networks:
  pgadmin_network:
    name: pgadmin_network
    external: true
  directus_network:
    name: directus_network
    external: true

configs:
  postgresql_config:
    file: ./initdb.d

services:

  postgresql:
    container_name: postgresql
    build:
      context: .
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    networks:
      - pgadmin_network
    configs:
      - source: postgresql_config
        target: /docker-entrypoint-initdb.d/
    volumes:
      - ./data/:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d ${POSTGRES_DB}'"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
