networks:
  boilerplate_network:
    external: true

services:
  smtp4dev:
    container_name: smtp4dev
    image: rnwood/smtp4dev:${SMTP4DEV_VERSION:-linux-amd64-3.3.4}
    networks:
      - boilerplate_network
    volumes:
      - ./data:/smtp4dev
    ports:
      - 25:25
      - 143:143
    environment:
      - ServerOptions__HostName=boilerplate.docker.org
      - ServerOptions__BasePath=/smtp4dev
    labels:
      traefik.enable: true
      traefik.http.routers.smtp4dev.entrypoints: websecure
      traefik.http.routers.smtp4dev.tls: true
      traefik.http.routers.smtp4dev.rule: ${SMTP4DEV_TRAEFIK_RULE}
      traefik.http.services.smtp4dev.loadbalancer.server.port: 8080

  mailpit:
    image: axllent/mailpit
    ports:
      - 1025
      - 8025
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
