networks:
  postgresql_internal:
    external: true
  proxy_internal:
    external: true

services:

  postgrest:
    container_name: postgrest
    image: postgrest/postgrest:${POSTGREST_VERSION:-v12.0.1}
    environment:
      PGRST_DB_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT:-5432}/${POSTGRES_DB}
      PGRST_DB_SCHEMAS: ${PGRST_DB_SCHEMAS:-public}
      PGRST_DB_ANON_ROLE: ${PGRST_DB_ANON_ROLE:-anon}
      PGRST_JWT_SECRET: ${PGRST_JWT_SECRET}
      PGRST_DB_USE_LEGACY_GUCS: ${PGRST_DB_USE_LEGACY_GUCS:-false}
      PGRST_APP_SETTINGS_JWT_SECRET: ${PGRST_APP_SETTINGS_JWT_SECRET}
      PGRST_APP_SETTINGS_JWT_EXP: ${PGRST_APP_SETTINGS_JWT_EXP}
    command: postgrest
    networks:
      - postgresql_internal
      - proxy_internal
    labels:
      traefik.enable: true
      traefik.http.routers.postgrest.entrypoints: websecure
      traefik.http.routers.postgrest.tls: true
      traefik.http.routers.postgrest.rule: ${POSTGREST_TRAEFIK_RULE}
      traefik.http.services.postgrest.loadbalancer.server.port: ${POSTGREST_PORT}
      traefik.http.middlewares.postgrest-strip.stripprefix.prefixes: /postgrest
      traefik.http.routers.postgrest.middlewares: postgrest-strip

  redocly:
    container_name: redocly
    image: redocly/redoc
    networks:
      - proxy_internal
    ports:
      - 8000:80
    environment:
      SPEC_URL: http://petstore.swagger.io/v2/swagger.json
