networks:
  postgresql_internal:
    external: true
  host_bridge:
    external: true

services:

  postgrest:
    container_name: postgrest
    image: postgrest/postgrest:${POSTGREST_VERSION:-v12.0.1}
    environment:
      PGRST_DB_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT:-5432}/${POSTGRES_DB}
      PGRST_DB_SCHEMAS: ${PGRST_DB_SCHEMAS:-public}
      PGRST_DB_ANON_ROLE: ${PGRST_DB_ANON_ROLE:-anon}
      PGRST_JWT_SECRET: ${PGRST_JWT_SECRET}
      PGRST_DB_USE_LEGACY_GUCS: ${PGRST_DB_USE_LEGACY_GUCS:-false}
      PGRST_APP_SETTINGS_JWT_SECRET: ${PGRST_APP_SETTINGS_JWT_SECRET}
      PGRST_APP_SETTINGS_JWT_EXP: ${PGRST_APP_SETTINGS_JWT_EXP}
    command: postgrest
    ports:
      - 3000:3000
    networks:
      - postgresql_internal
      - host_bridge
