services:

  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    volumes:
      - ./data:/home/node/.n8n
    ports:
      - 5678:5678

#DB_TYPE=postgresdb \
#DB_POSTGRESDB_DATABASE=<POSTGRES_DATABASE> \
#DB_POSTGRESDB_HOST=<POSTGRES_HOST> \
#DB_POSTGRESDB_PORT=<POSTGRES_PORT> \
#DB_POSTGRESDB_USER=<POSTGRES_USER> \
#DB_POSTGRESDB_SCHEMA=<POSTGRES_SCHEMA> \
#DB_POSTGRESDB_PASSWORD=<POSTGRES_PASSWORD> \
