services:
  webdev:
    labels:
      traefik.enable: true
      traefik.http.routers.webdev.rule: ${WEBDEV_TRAEFIK_RULE}
      traefik.http.services.webdev.loadbalancer.server.port: 80

networks:
  webdev_network:
    name: webdev_network
    driver: bridge
