networks:
  public-network:
  windev-internal:
    internal: true

volumes:
  hfsql-data:
  webdev-data:

services:
  hfsql:
    image: windev/hfsql:${HFSQL_VERSION}
    container_name: hfsql
    networks:
      - public-network
      - windev-internal
    volumes:
      - ./data/hfsql:/var/lib/hfsql
    ports:
      - 4900:4900
    environment:
      HFSQL_USER: ${HFSQL_USER}
      HFSQL_PASSWORD: ${HFSQL_PASSWORD}

  webdev:
    image: windev/webdev:${WEBDEV_VERSION}
    container_name: webdev
    networks:
      - proxy_internal
      - windev-internal
    #ports:
    #  - ${WEBDEV_PORT}:80
    volumes:
      - ./data/webdev:/var/lib/WEBDEV/29.0/
    depends_on:
      - hfsql

# http://127.0.0.1:8001/WDAdminWeb/
# User : webdevuser
# Password : Voir les logs Étape : 2/4
