  networks:
    k6:

  services:
  # siteinspector:
  #   image: siteinspector/siteinspector:latest
  #   container_name: siteinspector
  #   volumes:
  #     - uptime:/app/data
  #   ports:
  #     - 3001:3001

  k6:
    image: grafana/k6:0.47.0
    networks:
      - k6
    ports:
      - 6565:6565
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./examples:/scripts
