{
 "title": "Dragonfly",
 "tags": [
  "prometheus",
  "dragonfly"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Dragonfly",
    "query": {
     "query": "label_values(dragonfly_uptime_in_seconds,app)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(dragonfly_uptime_in_seconds{app=\"$Dragonfly\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(dragonfly_uptime_in_seconds{pod=~\"$instance\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dragonfly_connected_clients{pod=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (dragonfly_memory_used_bytes{pod=~\"$instance\"}  / dragonfly_memory_max_bytes{pod=~\"$instance\"} )"
    }
   ]
  },
  {
   "title": "IS MASTER?",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dragonfly_role{pod=\"$instance\", role=\"master\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commands Executed / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(dragonfly_commands_processed_total{pod=~\"$instance\"}[5m])"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "dragonfly_memory_used_bytes{pod=~\"$instance\"} ",
     "legendFormat": "used"
    },
    {
     "expr": "dragonfly_memory_max_bytes{pod=~\"$instance\"} ",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(dragonfly_net_input_bytes_total{pod=~\"$instance\"}[5m])",
     "legendFormat": "{{ input }}"
    },
    {
     "expr": "rate(dragonfly_net_output_bytes_total{pod=~\"$instance\"}[5m])",
     "legendFormat": "{{ output }}"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (dragonfly_db_keys{pod=~\"$instance\"}) by (db)",
     "legendFormat": "{{ db }} "
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (dragonfly_db_keys{pod=~\"$instance\"}) - sum (dragonfly_db_keys_expiring{pod=~\"$instance\"}) ",
     "legendFormat": "not expiring"
    },
    {
     "expr": "sum (dragonfly_db_keys_expiring{pod=~\"$instance\"})",
     "legendFormat": "expiring"
    }
   ]
  },
  {
   "title": "Rate of Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "irate(dragonfly_connections_received_total{pod=\"$instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dragonfly connected clients",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dragonfly_connected_clients{pod=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Hits / Misses / Hit Ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(dragonfly_keyspace_hits_total{pod=~\"$instance\"}[5m])",
     "legendFormat": "hits"
    },
    {
     "expr": "rate(dragonfly_keyspace_misses_total{pod=~\"$instance\"}[5m])",
     "legendFormat": "misses"
    },
    { "expression": "$A / ($A + $B) ", "type": "math" }
   ]
  },
  {
   "title": "Expired / Evicted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dragonfly_expired_keys_total{pod=~\"$instance\"}[5m])) by (instance)",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(rate(dragonfly_evicted_keys_total{pod=~\"$instance\"}[5m])) by (instance)",
     "legendFormat": "evicted"
    }
   ]
  }
 ]
}