{
 "title": "Kubernetes PHP-FPM",
 "description": "A companion dashboard for https://github.com/hipages/php-fpm_exporter\r\n\r\nThe dashboard caters to Kubernetes & PHP-FPM but can be easily adjusted.",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(phpfpm_up,kubernetes_namespace)"
   },
   {
    "name": "app",
    "label": "Application",
    "query": "phpfpm_up{kubernetes_namespace=\"$namespace\"}"
   },
   {
    "name": "branch",
    "label": "Branch",
    "query": "label_values(phpfpm_up{kubernetes_namespace=\"$namespace\",app=\"$app\"},hip_new)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Process Utilisation",
   "type": "gauge",
   "description": "Utilisation of processes based on active/inactive processes",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg((sum(phpfpm_active_processes{app=\"$app\",hip_new=\"$branch\"}) by (kubernetes_pod_name) *100) / sum(phpfpm_total_processes{app=\"$app\",hip_new=\"$branch\"}) by (kubernetes_pod_name))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Max Children reached",
   "type": "stat",
   "description": "How many times was the maximum amount of children reached?",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(phpfpm_max_children_reached{app=\"$app\",hip_new=\"$branch\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Accepted connections (rpm)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(phpfpm_accepted_connections{app=\"$app\",hip_new=\"$branch\"}[2m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "# of pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(phpfpm_up{app=\"$app\",hip_new=\"$branch\"} > 0)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Queued Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(phpfpm_listen_queue{app=\"$app\",hip_new=\"$branch\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Scrape failures",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(phpfpm_scrape_failures{app=\"$app\",hip_new=\"$branch\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "# of processes by state",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(phpfpm_process_state{app=\"$app\", hip_new=\"$branch\"}) by (state)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{state}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(phpfpm_process_state{app=\"$app\", hip_new=\"$branch\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Request Duration by process",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(phpfpm_process_request_duration{app=\"$app\",hip_new=\"$branch\"}) by (pid_hash)",
     "legendFormat": "{{pid_hash}}",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Queued requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(phpfpm_listen_queue{app=\"$app\",hip_new=\"$branch\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "# of requests",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Requests per process",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(phpfpm_process_requests{app=\"$app\", hip_new=\"$branch\"}) by (pid_hash)",
     "legendFormat": "{{pid_hash}}",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "# of Active & Idle processes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(phpfpm_active_processes{app=\"$app\", hip_new=\"$branch\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "# of active processes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(phpfpm_idle_processes{app=\"$app\", hip_new=\"$branch\"})",
     "legendFormat": "# of idle processes"
    },
    {
     "expr": "sum(phpfpm_total_processes{app=\"$app\", hip_new=\"$branch\"})",
     "legendFormat": "# of total processes"
    }
   ]
  },
  {
   "title": "Total process utilisation & container termination",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percent", "label": "Process utilisation" }
   ],
   "targets": [
    {
     "expr": "avg((sum(phpfpm_active_processes{app=\"$app\",hip_new=\"$branch\"}) by (kubernetes_pod_name) *100) / sum(phpfpm_total_processes{app=\"$app\",hip_new=\"$branch\"}) by (kubernetes_pod_name))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Process utilisation",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(kube_pod_container_status_terminated{pod=~\"static-thread-handling-.*\"})",
     "legendFormat": "# of pod terminations"
    }
   ]
  },
  {
   "title": "# of pods in a ReplicaSet",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kube_replicaset_spec_replicas{replicaset=~\"$branch-.*\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{replicaset}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count(container_memory_usage_bytes{pod_name=~\"$branch-.*\", namespace=\"$namespace\"}) by (pod_name))",
     "legendFormat": "pods"
    },
    {
     "expr": "count(count(container_memory_usage_bytes{pod_name=~\"$branch-.*\", namespace=\"$namespace\"}) by (kubernetes_io_hostname))",
     "legendFormat": "hosts"
    }
   ]
  },
  {
   "title": "Cpu usage (relative to limit)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container_name=\"fpm\",pod_name=~\"$branch-.*\", namespace=\"$namespace\"}[30s])) by (namespace,container_name) / sum(container_spec_cpu_quota{container_name=\"fpm\",pod_name=~\"$branch-.*\", namespace=\"$namespace\"} / container_spec_cpu_period{container_name=\"$container\", namespace=\"$namespace\"}) by (namespace,container_name)",
     "legendFormat": "actual"
    }
   ]
  },
  {
   "title": "Memory usage (relative to limit)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_name=\"fpm\",pod_name=~\"$branch-.*\", namespace=\"$namespace\"}) by (namespace,container_name) / sum(container_spec_memory_limit_bytes{container_name=\"fpm\",pod_name=~\"$branch-.*\", namespace=\"$namespace\"}) by (namespace,container_name)",
     "legendFormat": "actual"
    }
   ]
  },
  {
   "title": "CPU usage per pod (relative to limit)",
   "type": "graph",
   "description": "The metric may not work if there is no quota assigned.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  irate(\n    container_cpu_usage_seconds_total{container_name=\"fpm\", namespace=\"$namespace\",pod_name=~\"$branch-.*\"}[2m]\n  )\n) by (namespace,container_name,pod_name) /\nsum(\n  container_spec_cpu_quota{container_name=\"fpm\",namespace=\"$namespace\",pod_name=~\"$branch-.*\"} /\n  container_spec_cpu_period{container_name=\"fpm\",namespace=\"$namespace\",pod_name=~\"$branch-.*\"}\n) by (namespace,container_name,pod_name)",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Memory usage per pod (relative to limit)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_name=\"fpm\",pod_name=~\"$branch-.*\"}) by (namespace,container_name,pod_name) / sum(container_spec_memory_limit_bytes{container_name=\"fpm\",pod_name=~\"$branch-.*\"}) by (namespace,container_name,pod_name)",
     "legendFormat": "{{pod_name}}",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Cpu usage (per pod)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{pod_name=~\"$branch-.*\",container_name=\"fpm\", namespace=\"$namespace\"}[30s])) by (id,pod_name)",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "sum(container_spec_cpu_quota{pod_name=~\"$branch-.*\",container_name=\"fpm\", namespace=\"$namespace\"} / container_spec_cpu_period{pod_name=~\"$branch-.*\",container_name=\"fpm\", namespace=\"$namespace\"}) by (namespace,container_name) / count(container_memory_usage_bytes{pod_name=~\"$branch-.*\",container_name=\"fpm\", namespace=\"$namespace\"}) by (namespace,container_name) ",
     "legendFormat": "limit"
    },
    {
     "expr": "sum(container_spec_cpu_shares{pod_name=~\"$branch-.*\",container_name=\"fpm\", namespace=\"$namespace\"} / 1024) by (namespace,container_name) / count(container_spec_cpu_shares{pod_name=~\"$branch-.*\",container_name=\"fpm\", namespace=\"$namespace\"}) by (namespace,container_name) ",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory usage (avg per pod)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod_name=~\"$branch-.*\",container_name=\"fpm\", namespace=\"$namespace\"}) by (namespace,container_name) / count(container_memory_usage_bytes{pod_name=~\"$branch-.*\",container_name=\"fpm\", namespace=\"$namespace\"}) by (namespace,container_name) ",
     "legendFormat": "actual"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{pod_name=~\"$branch-.*\",container_name=\"fpm\", namespace=\"$namespace\"}) by (namespace,container_name) / count(container_memory_usage_bytes{pod_name=~\"$branch-.*\",container_name=\"fpm\", namespace=\"$namespace\"}) by (namespace,container_name) ",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Cpu usage (total)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{pod_name=~\"$branch-.*\",container_name=\"fpm\", namespace=\"$namespace\"}[30s])) by (namespace,container_name)",
     "legendFormat": "actual"
    },
    {
     "expr": "sum(container_spec_cpu_quota{pod_name=~\"$branch-.*\",container_name=\"fpm\", namespace=\"$namespace\"} / container_spec_cpu_period{pod_name=~\"$branch-.*\",container_name=\"fpm\", namespace=\"$namespace\"}) by (namespace,container_name)",
     "legendFormat": "limit"
    },
    {
     "expr": "sum(container_spec_cpu_shares{pod_name=~\"$branch-.*\",container_name=\"fpm\", namespace=\"$namespace\"} / 1024) by (namespace,container_name) ",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory usage (total)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod_name=~\"$branch-.*\",container_name=\"fpm\", namespace=\"$namespace\"}) by (namespace,container_name)",
     "legendFormat": "actual"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{pod_name=~\"$branch-.*\",container_name=\"fpm\", namespace=\"$namespace\"}) by (namespace,container_name)",
     "legendFormat": "limit"
    }
   ]
  }
 ]
}