configs:
  mariadb_initdb:
    file: ./mariadb/docker-entrypoint-initdb.d

services:

# MariaDB Server
# https://mariadb.org/

  mariadb:
    container_name: r5a10-mariadb
    build:
      context: ./mariadb
    restart: no
    configs:
      - source: mariadb_initdb
        target: /docker-entrypoint-initdb.d
    volumes:
      - ./data/mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}

  nocodb:
    container_name: r5a10-nocodb
    image: nocodb/nocodb:latest
    ports:
      - 8080:8080
    environment:
      NC_DB: mysql://mariadb
      NC_ADMIN_EMAIL: ${ADMIN_EMAIL}
      NC_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
