configs:
  mariadb_initdb:
    file: ./mariadb/docker-entrypoint-initdb.d

services:

# MariaDB Server
# https://mariadb.org/

  mariadb:
    container_name: r5a10-mariadb
    build:
      context: ./mariadb
    restart: no
    configs:
      - source: mariadb_initdb
        target: /docker-entrypoint-initdb.d
    volumes:
      - ./data/mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
