services:

  gitea:
    container_name: gitea
    image: gitea/${GITEA_VERSION}
    restart: always
    volumes:
      - ./data:/var/lib/gitea
      - ./config:/etc/gitea
    ports:
      - 3000:3000
      - 2222:2222

  runner-1:
    container_name: runner-1
    image: gitea/act_runner:latest
