networks:
  boilerplate_network:
    external: true

configs:
  ntfy_config:
    file: server.yml

services:

  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    environment:
      TZ: Europe/Paris
      NTFY_BASE_URL: https://ntfy.docker.org
      NTFY_SMTP_SENDER_ADDR: smtp4dev:25
      NTFY_SMTP_SENDER_FROM: boilerplate@docker.org
    volumes:
      - ./data/ntfy/cache:/var/cache/ntfy
    configs:
      - source: ntfy_config
        target: /etc/ntfy/server.yml
    networks:
      - boilerplate_network
    healthcheck: # optional: remember to adapt the host:port to your environment
        test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
        interval: 60s
        timeout: 10s
        retries: 3
        start_period: 40s
    labels:
      traefik.enable: true
      traefik.http.routers.ntfy.entrypoints: websecure
      traefik.http.routers.ntfy.tls: true
      traefik.http.routers.ntfy.rule: ${NTFY_TRAEFIK_RULE}
      traefik.http.services.ntfy.loadbalancer.server.port: ${NTFY_PORT}
