services:
  axelor:
    image: axelor/aos-preview-app
    ports:
      - 8086:8080
    environment:
      APP_LANGUAGE: fr
      APP_DEMO_DATA: true
      APP_LOAD_APPS: true
    volumes:
      - ./data/aos:/app/data \
      - ./data/postgresql:/var/lib/postgresql \
