networks:
  boilerplate_network:
    external: true

services:

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    container_name: dragonfly
    ulimits:
      memlock: -1
    ports:
      - ${DRAGONFLY_PORT:-6379}:6379
    networks:
      - boilerplate_network
    volumes:
      - ./data/:/data/
