networks:

  proxy_network:
    name: proxy_network
    driver: bridge

services:

  traefik:
    image: traefik:${TRAEFIK_VERSION}
    container_name: traefik
    command:
      - "--entrypoints.web.address=:80"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      #- "--log.level=DEBUG"
    restart: unless-stopped
    environment:
      TZ: Europe/Paris
    ports:
      - 80:80
      #- 8080:8080 # Dashboard port
    labels:
      traefik.enable: true
      traefik.http.routers.api.rule: ${DASHBOARD_TRAEFIK_RULE}
      traefik.http.routers.api.entryPoints: web
      traefik.http.routers.api.service: api@internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
     - proxy_network

  whoami:
    image: traefik/whoami
    container_name: whoiam
    labels:
      traefik.enable: true
      traefik.http.routers.whoami.rule: ${WHOIAM_TRAEFIK_RULE}
      traefik.http.routers.whoami.entrypoints: web
    networks:
     - proxy_network
