networks:
  proxy_bridge:
    name: proxy
    driver: bridge
  proxy_internal:
    name: proxy_internal
    internal: true

configs:
  certs_files:
    file: ./certs
  certs_config:
    file: ./certs-traefik.yml

x-logging:
  &default-logging
    driver: loki
    options:
      loki-url: http://localhost:3100/loki/api/v1/push
      loki-external-labels: job=docker,container={{.Name}},environment=development
      loki-retries: 5
      loki-max-backoff: 800ms
      loki-timeout: 1s
      keep-file: 'true'

services:

  traefik:
    image: traefik:${TRAEFIK_VERSION}
    container_name: traefik
    command:
      - "--entrypoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--api"

      - "--ping=true"
      - "--ping.entryPoint=web"

      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy_internal"
      - "--providers.file.directory=/etc/traefik/dynamic"

      - "--metrics=true"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.entryPoint=web"
      - "--metrics.prometheus.addEntryPointsLabels=true"
      - "--metrics.prometheus.addServicesLabels=true"
    #  - "--log.level=DEBUG"
    restart: unless-stopped
    environment:
      TZ: Europe/Paris
    ports:
      - 80:80
      - 443:443
    configs:
      - source: certs_files
        target: /etc/certs/
      - source: certs_config
        target: /etc/traefik/dynamic/certs-traefik.yml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy_bridge
      - proxy_internal
    labels:
      traefik.enable: true
      traefik.http.routers.api.entryPoints: websecure
      traefik.http.routers.api.tls: true
      traefik.http.routers.api.rule: ${DASHBOARD_TRAEFIK_RULE}
      traefik.http.routers.api.service: api@internal
    logging:
      << : *default-logging

  whoami:
    image: traefik/whoami
    container_name: whoami
    networks:
      - proxy_internal
    ports:
      - 8081:80
    depends_on:
      - traefik
    labels:
      traefik.enable: true
      traefik.http.routers.whoami.entrypoints: websecure
      traefik.http.routers.whoami.tls: true
      traefik.http.routers.whoami.rule: ${WHOAMI_TRAEFIK_RULE}
      traefik.http.services.whoami.loadbalancer.server.port: 80
