networks:
  proxy_network:
    name: proxy_network
    external: true

services:

    grafana:
      networks:
        - proxy_network
      labels:
        traefik.enable: true
        traefik.http.routers.grafana.entrypoints: web
        traefik.http.routers.grafana.rule: ${GRAFANA_TRAEFIK_RULE}
        traefik.http.services.grafana.loadbalancer.server.port: 3000

    prometheus:
      networks:
        - proxy_network
      labels:
        traefik.enable: true
        traefik.http.routers.prometheus.entrypoints: web
        traefik.http.routers.prometheus.rule: ${PROMETHEUS_TRAEFIK_RULE}
        traefik.http.services.prometheus.loadbalancer.server.port: 9090
