volumes:
  uptime:
#  grafana:
#  prometheus:

#configs:
#  prometheus_config:
#    file: prometheus/prometheus.yml

networks:
  k6:

services:

  uptime:
    image: louislam/uptime-kuma:1.23.8-alpine
    container_name: uptime
    volumes:
      - uptime:/app/data
    ports:
      - 3001:3001
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss:10.0.0
    container_name: grafana
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana_datasources:/etc/grafana/provisioning/datasources
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped

#  prometheus:
#    image: prom/prometheus:v2.44.0
#    container_name: prometheus
#    command:
#      - '--config.file=/etc/prometheus/prometheus.yml'
#    configs:
#      - source: prometheus_config
#        target: /etc/prometheus/prometheus.yml
#    volumes:
#      - prometheus:/prometheus
#    ports:
#      - 9090:9090
#    restart: unless-stopped

  siteinspector:
    image: siteinspector/siteinspector:latest
    container_name: siteinspector
    volumes:
      - uptime:/app/data
    ports:
      - 3001:3001

  k6:
    image: grafana/k6:0.47.0
    networks:
      - k6
    ports:
      - 6565:6565
  #  environment:
  #    - K6_OUT=influxdb=http://influxdb:8086/k6
  #  volumes:
  #    - ./examples:/scripts

# based on https://github.com/docker/awesome-compose/tree/master/prometheus-grafana
# https://github.com/stefanprodan/dockprom
# https://yoandev.co/superviser-ses-conteneurs-docker-avec-prometheus/grafana-et-stressons-la-solution-avec-une-api-symfony-et-postman/
