services:

    grafana:
      labels:
        traefik.enable: true
        traefik.http.routers.grafana.entrypoints: web
        traefik.http.routers.grafana.rule: PathPrefix(`/grafana`)
        traefik.http.services.grafana.loadbalancer.server.port: 80

    prometheus:
      labels:
        traefik.enable: true
        traefik.http.routers.prometheus.entrypoints: web
        traefik.http.routers.prometheus.rule: PathPrefix(`/prometheus`)
        traefik.http.services.prometheus.loadbalancer.server.port: 9090
