networks:
  proxy_network:
    name: proxy_network
    external: true

services:

    grafana:
      networks:
        - proxy_network
      labels:
        traefik.enable: true
        traefik.http.routers.grafana.entrypoints: web
        traefik.http.routers.grafana.rule: ${GRAFANA_TRAEFIK_RULE}
        traefik.http.services.grafana.loadbalancer.server.port: ${GRAFANA_PORT}

    prometheus:
      networks:
        - proxy_network
      labels:
        traefik.enable: true
        traefik.http.routers.prometheus.entrypoints: web
        traefik.http.routers.prometheus.rule: ${PROMETHEUS_TRAEFIK_RULE}
        traefik.http.services.prometheus.loadbalancer.server.port: ${PROMETHEUS_PORT}

    loki:
      networks:
        - proxy_network
    
    minio:
      networks:
        - proxy_network
      labels:
        traefik.enable: true
        traefik.http.routers.minio.entrypoints: web
        traefik.http.routers.minio.rule: ${MINIO_TRAEFIK_RULE}
        traefik.http.services.minio.loadbalancer.server.port: ${MINIO_PORT}

    minio_init:
      networks:
        - proxy_network