networks:
  postgraphile_host:
    name: postgraphile_host
    driver: bridge
  postgresql_internal:
    external: true

services:

  postgraphile:
    image: cinema/postgraphile:2024.03
    container_name: postgraphile
    build:
      context: ./postgraphile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_SCHEMA=${DATABASE_SCHEMA}
    ports:
      - 8003:5433
    networks:
      - postgresql_internal
      - postgraphile_host
    command:
      [
        "--connection",
        "${DATABASE_URL}",
        "--port", "5433",
        "--schema", "public,${DATABASE_SCHEMA}",
        "--enhance-graphiql",
        "--cors",
        "--allow-explain",
        "--dynamic-json",
        "--append-plugins",
        "postgraphile-plugin-connection-filter,postgraphile-plugin-fulltext-filter,@graphile/postgis,postgraphile-plugin-connection-filter-postgis"
      ]
