networks:
  postgresql_internal:
    external: true
  proxy_internal:
    external: true

services:

  postgraphile:
    image: boilerplate/postgraphile:2024.03
    container_name: postgraphile
    build:
      context: ./
    environment:
      - PGHOST=${PGHOST}
      - PGPORT=${PGPORT:-5432}
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
    networks:
      - postgresql_internal
      - proxy_internal
    command:
      [
        "--port", "${POSTGRAPHILE_PORT:-5000}",
        "--graphql", "/postgraphile/graphql",
        "--graphiql", "/postgraphile/graphiql",
        "--schema", "${POSTGRAPHILE_SCHEMA}",
        "--enhance-graphiql",
        "--cors",
        "--allow-explain",
        "--dynamic-json",
        "--append-plugins",
        "postgraphile-plugin-connection-filter,postgraphile-plugin-fulltext-filter,@graphile/postgis,postgraphile-plugin-connection-filter-postgis"
      ]
    labels:
      traefik.enable: true
      traefik.http.routers.postgraphile.entrypoints: websecure
      traefik.http.routers.postgraphile.tls: true
      traefik.http.routers.postgraphile.rule: ${POSTGRAPHILE_TRAEFIK_RULE}
      traefik.http.services.postgraphile.loadbalancer.server.port: ${POSTGRAPHILE_PORT}
