services:

  apache:
    container_name: nextcloud-apache
    image: nextcloud/apache:2024.04
    build:
      context: ./apache
    ports:
      - 8000:80
    volumes:
      - ./data:/var/www/html

  php:
    container_name: nextcloud-php
    image: nextcloud/php:2024.04
    build:
      context: ./php
    volumes:
      - ./data:/var/www/html
