services:

  apache:
    container_name: nextcloud-apache
    image: nextcloud/apache:2024.04
    build:
      context: ./apache
    ports:
      - 8000:80
    volumes:
      - ./data:/var/www/html
    labels:
      traefik.enable: true
      traefik.http.routers.nextcloud.entrypoints: websecure
      traefik.http.routers.nextcloud.tls: true
      traefik.http.routers.nextcloud.rule: ${NEXTCLOUD_TRAEFIK_RULE}
      traefik.http.services.nextcloud.loadbalancer.server.port: 80

  php:
    container_name: nextcloud-php
    image: nextcloud/php:2024.04
    build:
      context: ./php
    volumes:
      - ./data:/var/www/html
