services:

  pgadmin:
    environment:
      SCRIPT_NAME: /pgadmin
    labels:
      traefik.enable: true
      traefik.http.routers.pgadmin.entrypoints: websecure
      traefik.http.routers.pgadmin.tls: true
      traefik.http.routers.pgadmin.rule: ${PGADMIN_TRAEFIK_RULE}
      traefik.http.services.pgadmin.loadbalancer.server.port: 80
