networks:
  proxy_internal:
    name: proxy_internal
    external: true

services:

  pgadmin:
    networks:
      - proxy_internal
    environment:
      SCRIPT_NAME: /pgadmin
    labels:
      traefik.enable: true
      traefik.http.services.pgadmin.loadbalancer.server.port: 80
      traefik.http.routers.pgadmin.rule: ${PGADMIN_TRAEFIK_RULE}
      traefik.http.routers.pgadmin.entrypoints: web
