networks:
  postgresql_internal:
    external: true
  proxy_internal:
    external: true

configs:
  pgadmin_config:
    file: ./pgadmin-servers.json

services:

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:${PGADMIN_VERSION:-8.4}
    restart: no
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_DISABLE_POSTFIX: true
    configs:
      - source: pgadmin_config
        target: /pgadmin4/servers.json
    volumes:
      - ./data/:/var/lib/pgadmin/
    networks:
      - proxy_internal
      - postgresql_internal
