volumes:
  uptime_data:

services:

  uptime:
    image: louislam/uptime-kuma:1.23.2-alpine
    container_name: uptime
    volumes:
      - uptime_data:/app/data
    ports:
      - 3001:3001
    restart: unless-stopped
