networks:
  proxy_network:
    name: proxy_network
    external: true

services:

  uptime:
    networks:
      - proxy_network
    labels:
      traefik.enable: true
      traefik.http.services.uptime.loadbalancer.server.port: 3001
      traefik.http.routers.uptime.rule: ${UPTIME_TRAEFIK_RULE}

