networks:
  proxy_internal:
    name: proxy_internal
    external: true

services:

  uptime:
    networks:
      - proxy_internal
    labels:
      traefik.enable: true
      traefik.http.services.uptime.loadbalancer.server.port: 3001
      traefik.http.routers.uptime.rule: ${UPTIME_TRAEFIK_RULE}
