services:

  uptime:
    container_name: uptime
    image: louislam/uptime-kuma:${UPTIME_VERSION}
    #ports:
    #  - ${UPTIME_PORT}:3001
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    labels:
      traefik.enable: true
      traefik.http.services.uptime.loadbalancer.server.port: 3001
      traefik.http.routers.uptime.rule: ${UPTIME_TRAEFIK_RULE}
