services:

  uptime:
    container_name: uptime
    image: louislam/uptime-kuma:${UPTIME_VERSION}
    ports:
      - ${UPTIME_PORT}:3001
    restart: unless-stopped
    volumes:
      - ./data:/app/data
