services:

  mongodb:
    container_name: mongodb
    image: mongo:${MONGODB_VERSION:-7.0.7-jammy}
    volumes:
      - ./data/configdb:/data/configdb
      - ./data/db:/data/db
    ports:
      - ${MONGODB_PORT:-27017}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
