services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./data/configdb:/data/configdb
      - /data/db:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ivfGUPFKsB97y7ka9zsZ
