networks:
  boilerplate_network:
    external: true

services:

  directus:
    container_name: directus
    image: directus/directus:${DIRECTUS_VERSION:-10.11}
    networks:
      - boilerplate_network
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      KEY: ${DIRECTUS_KEY}
      SECRET: ${DIRECTUS_SECRET}
      PUBLIC_URL: https://directus.docker.org/
      PORT: ${DIRECTUS_PORT}

      DB_CLIENT: ${DIRECTUS_DB_CLIENT}
      DB_HOST: ${DIRECTUS_DB_HOST}
      DB_PORT: ${DIRECTUS_DB_PORT}
      DB_DATABASE: ${DIRECTUS_DB_DATABASE}
      DB_USER: ${DIRECTUS_DB_USER}
      DB_PASSWORD: ${DIRECTUS_DB_PASSWORD}

      CACHE_ENABLED: true
      CACHE_STORE: redis
      REDIS: redis://dragonfly:6379

      ADMIN_EMAIL: ${DIRECTUS_EMAIL}
      ADMIN_PASSWORD: ${DIRECTUS_PASSWORD}

      EMAIL_FROM: boilerplate@docker.org
      EMAIL_TRANSPORT: smtp
      EMAIL_SMTP_HOST: ${DIRECTUS_SMTP_HOST}
      EMAIL_SMTP_PORT: ${DIRECTUS_SMTP_PORT}
      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      # PUBLIC_URL: "https://directus.example.com"

    labels:
      traefik.enable: true
      traefik.http.routers.directus.entrypoints: websecure
      traefik.http.routers.directus.tls: true
      traefik.http.services.directus.loadbalancer.server.port: ${DIRECTUS_PORT}
      traefik.http.routers.directus.rule: ${DIRECTUS_TRAEFIK_RULE}
