networks:
  proxy_network:
    name: proxy_network
    external: true

services:

  directus:
    networks:
      - proxy_network
    labels:
      traefik.enable: true
      traefik.http.services.directus.loadbalancer.server.port: 80
      traefik.http.routers.directus.rule: ${DIRECTUS_TRAEFIK_RULE}
      traefik.http.routers.directus.entrypoints: web
