networks:
  directus_network:
    name: directus_network
    driver: bridge
    internal: true

services:

  cache:
    container_name: redis
    image: redis:6

  directus:
    container_name: directus
    image: directus/directus:${DIRECTUS_VERSION}
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    depends_on:
      - cache
    environment:
      KEY: "255d861b-5ea1-5996-9aa3-922530ec40b1"
      SECRET: "6116487b-cda1-52c2-b5b5-c8022c45e263"

      DB_CLIENT: "pg"
      DB_HOST: "postgresql"
      DB_PORT: 5432
      DB_DATABASE: "postgres"
      DB_USER: "postgres"
      DB_PASSWORD: "supermotdepasse"

      CACHE_ENABLED: "true"
      CACHE_STORE: redis
      REDIS: "redis://cache:6379"

      ADMIN_EMAIL: ${DIRECTUS_EMAIL}
      ADMIN_PASSWORD: ${DIRECTUS_PASSWORD}

      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      # PUBLIC_URL: "https://directus.example.com"
