
services:

  directus:
    labels:
      traefik.enable: true
      traefik.http.routers.directus.entrypoints: websecure
      traefik.http.routers.directus.tls: true
      traefik.http.services.directus.loadbalancer.server.port: ${DIRECTUS_PORT}
      traefik.http.routers.directus.rule: ${DIRECTUS_TRAEFIK_RULE}
