services:

  elastic-node1:
    container_name: elastic-node1
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    ports:
      - 9200:9200
    environment:
      cluster.name: ${ELASTIC_CLUSTER_NAME}
      http.port: 9200
      discovery.type: single-node
      http.max_content_length: 10MB
      http.cors.enabled: true
      http.cors.allow-origin: \*
      http.cors.allow-headers: X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      http.cors.allow-credentials: true
      network.publish_host: localhost
      xpack.security.enabled: false
