services:

  nodered:
    image: nodered/node-red:3.1
    container_name: nodered
    environment:
      TZ: Europe/Paris
    ports:
      - 1880:1880
    volumes:
      - ./data:/data
    labels:
      traefik.enable: true
      traefik.http.services.nodered.loadbalancer.server.port: 1880
      traefik.http.routers.nodered.rule: ${NODERED_TRAEFIK_RULE}
      traefik.http.routers.nodered.entrypoints: web
