services:

  nodered:
    image: nodered/node-red:${NODERED_VERSION:-3.1}
    container_name: nodered
    environment:
      TZ: Europe/Paris
    ports:
      - 1880:1880
    volumes:
      - ./data:/data
