networks:
  proxy_internal:
    name: proxy_internal
    external: true

services:

  nodered:
    networks:
      - proxy_internal
    labels:
      traefik.enable: true
      traefik.http.services.nodered.loadbalancer.server.port: ${NODERED_PORT}
      traefik.http.routers.nodered.rule: ${NODERED_TRAEFIK_RULE}
      traefik.http.routers.nodered.entrypoints: web
