networks:
  boilerplate_bridge:
    external: true

configs:
  nodered_settings:
    file: ./settings.js

services:

  nodered:
    image: nodered/node-red:${NODERED_VERSION:-3.1}
    container_name: nodered
    environment:
      TZ: Europe/Paris
    configs:
      - source: nodered_settings
        target: /data/settings.js
    volumes:
      - ./data:/data
    networks:
      - boilerplate_bridge
    labels:
      traefik.enable: true
      traefik.http.routers.nodered.entrypoints: websecure
      traefik.http.routers.nodered.tls: true
      traefik.http.routers.nodered.rule: ${NODERED_TRAEFIK_RULE}
      traefik.http.services.nodered.loadbalancer.server.port: ${NODERED_PORT}
