x-logging:
  &default-logging
  driver: loki
  options:
    loki-url: http://localhost:3100/loki/api/v1/push
    loki-external-labels: job=fakelog,environment=development

services:
  fakelog:
    image: mingrammer/flog
    container_name: fake_logs
    command:
      - --loop
      - --format=json
      - --number=1
      - --delay=500ms
      - --overwrite
      - --type=stdout
    logging: *default-logging
