networks:
  boilerplate_network:
    external: true

services:

  fusionauth:
    image: fusionauth/fusionauth-app:latest
    container_name: fusionauth-app
    environment:
      DATABASE_URL: jdbc:postgresql://postgresql:5432/fusionauth
      DATABASE_ROOT_USERNAME: ${POSTGRES_USER}
      DATABASE_ROOT_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      FUSIONAUTH_APP_MEMORY: ${FUSIONAUTH_APP_MEMORY}
      FUSIONAUTH_APP_RUNTIME_MODE: development
      FUSIONAUTH_APP_URL: http://fusionauth:9011
      SEARCH_TYPE: database
    ports:
      - 9011:9011
    networks:
      - boilerplate_network
    volumes:
      - ./data:/usr/local/fusionauth/config
