networks:
  boilerplate_network:
    external: true

services:

  excalibur-apache:
    container_name: apache
    image: excalibur/apache
    build:
      context: .
    volumes:
      - ./www:/var/www/html
    ports:
      - 8001:80
    networks:
      - boilerplate_network
