networks:
  boilerplate_network:
    external: true

configs:
  postgresql_initdb:
    file: ./initdb.d

services:

  postgresql:
    image: boilerplate/madlib:${POSTGRES_VERSION}
    container_name: madlib-postgresql
    build:
      context: .
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 54321:5432
    networks:
      - boilerplate_network
    configs:
      - source: postgresql_initdb
        target: /docker-entrypoint-initdb.d/
    volumes:
      - ./data/postgresql/:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d ${POSTGRES_DB}'"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
