networks:
  boilerplate_network:
    external: true

services:

  mongodb:
    networks:
      - boilerplate_network

  datanode:
    networks:
      - boilerplate_network

  graylog:
    networks:
      - boilerplate_network
    labels:
      traefik.enable: true
      traefik.http.services.graylog.loadbalancer.server.port: 9000
      traefik.http.routers.graylog.rule: ${GRAYLOG_TRAEFIK_RULE}
      traefik.http.routers.graylog.entrypoints: web
