networks:
  proxy_internal:
    name: proxy_internal
    external: true

services:

  mongodb:
    networks:
      - proxy_internal

  datanode:
    networks:
      - proxy_internal

  graylog:
    networks:
      - proxy_internal
    labels:
      traefik.enable: true
      traefik.http.services.graylog.loadbalancer.server.port: 9000
      traefik.http.routers.graylog.rule: ${GRAYLOG_TRAEFIK_RULE}
      traefik.http.routers.graylog.entrypoints: web
