services:

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.12.2
    ports:
      - 9200:9200

  kibana:
    container_name: kibana
    image: kibana:8.12.2
    ports:
      - 5601:5601
