networks:
  host_bridge:
    external: true
  postgresql_internal:
    external: true

services:
  ferretdb:
    image: ghcr.io/ferretdb/ferretdb
    container_name: ferretdb
    ports:
      - 27017:27017
    networks:
      - host_bridge
      - postgresql_internal
    environment:
      FERRETDB_POSTGRESQL_URL: ${FERRETDB_POSTGRESQL_URL}
