networks:
  boilerplate_network:
    external: true

services:

  mariadb:
    image: mariadb:${MARIADB_VERSION:-11.0}
    container_name: mariadb
    restart: no
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - boilerplate_network
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}

  phpmyadmin:
    image: phpmyadmin:${PHPMYADMIN_VERSION}
    container_name: phpmyadmin
    depends_on:
      - mariadb
    restart: no
    networks:
      - boilerplate_network
    environment:
      #PMA_ARBITRARY: 1 # Allowing you to specify any MySQL/MariaDB server on the login page.
      PMA_HOST: mariadb
      PMA_ABSOLUTE_URI: https://localhost/phpmyadmin/
    labels:
      traefik.enable: true
      traefik.http.routers.phpmyadmin.entrypoints: websecure
      traefik.http.routers.phpmyadmin.tls: true
      traefik.http.routers.phpmyadmin.rule: ${PHPMYADMIN_TRAEFIK_RULE}
      traefik.http.services.phpmyadmin.loadbalancer.server.port: 80
      traefik.http.middlewares.phpmyadmin-strip.stripprefix.prefixes: /phpmyadmin
      traefik.http.middlewares.phpmyadmin-strip.stripprefix.forceslash: false
      traefik.http.routers.phpmyadmin.middlewares: phpmyadmin-strip
