volumes:
#  pg_data:
#  mariadb_data:

networks:
  default:
    name: admin_net
    external: true

services:

  mariadb:
    image: mariadb:${MARIADB_VERSION:-11.0}
    container_name: server_mariadb
    restart: no
  volumes:
    - mariadb_data:/var/lib/mysql
  environment:
    MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    MARIADB_USER: ${MARIADB_USER}
    MARIADB_PASSWORD: ${MARIADB_PASSWORD}

  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: phpmyadmin
    restart: no
    ports:
      - 8002:80
    environment:
      PMA_ARBITRARY: 1 # Allowing you to specify any MySQL/MariaDB server on the login page.
