route:
  receiver: 'mail'
  repeat_interval: 15m
  group_by: [ alertname ]


receivers:
  - name: 'mail'
    email_configs:
      - smarthost: 'smtp:25'
        from: 'alert@docker.org'
        to: 'boilerplate@docker.org'
