networks:
  boilerplate_network:
    external: true

services:

  matomo:
    container_name: matomo
    image: matomo
    networks:
      - boilerplate_network
    environment:
      MATOMO_DATABASE_ADAPTER: ${MATOMO_DATABASE_ADAPTER}
      MATOMO_DATABASE_HOST: ${MATOMO_DATABASE_HOST}
      MATOMO_DATABASE_DBNAME: ${MATOMO_DATABASE_DBNAME}
      MATOMO_DATABASE_USERNAME: ${MATOMO_DATABASE_USERNAME}
      MATOMO_DATABASE_PASSWORD: ${MATOMO_DATABASE_PASSWORD}
    labels:
      traefik.enable: true
      traefik.http.routers.matomo.entrypoints: websecure
      traefik.http.routers.matomo.tls: true
      traefik.http.routers.matomo.rule: ${MATOMO_TRAEFIK_RULE}
      traefik.http.services.matomo.loadbalancer.server.port: 80
      traefik.http.routers.matomo.middlewares: strip-prefix
