networks:
  boilerplate_network:
    external: true

services:

  minio:
    container_name: minio
    image: minio/minio
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_DEFAULT_BUCKETS: loki
      MINIO_BROWSER_LOGIN_ANIMATION: off
      MINIO_PROMETHEUS_AUTH_TYPE: public
      MINIO_PROMETHEUS_URL: http://prometheus:9090/prometheus
      MINIO_PROMETHEUS_JOB_ID: minio
    volumes:
      - ./data:/data
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - boilerplate_network
    labels:
      traefik.enable: true
      traefik.http.routers.minio.entrypoints: websecure
      traefik.http.routers.minio.tls: true
      traefik.http.routers.minio.rule: ${MINIO_TRAEFIK_RULE}
      traefik.http.services.minio.loadbalancer.server.port: ${MINIO_PORT}

    #healthcheck:
    #  test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
    #  interval: 15s
    #  timeout: 20s
    #  retries: 5
    #logging: *default-logging
