networks:
  boilerplate_network:
    external: true

services:
  redis:
    container_name: redis
    image: redis:7.2-alpine
    command:
      - 'redis-server'
      - '--save 60 1'
      - '--loglevel warning'
      - '--requirepass supermotdepasse'
    networks:
      - boilerplate_network
    volumes:
      - ./data:/data
