version: '3.9'

services:

  apache:
    image: httpd:2.4

  mariadb:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=phprs
      - MYSQL_DATABASE=phprs
